package model;
public enum Rules {
    INSUFFICIENT_BALANCE,
    TRANSACTION_MAX_LIMIT,
    INVALID_TRANSFER_AMOUNT,
    INVALID_ACCOUNT_NUMBER,
    TRANS_AMOUNT_GREATER_THAN_BALANCE,
    INVALID_CARD_NO_OR_PIN_NO, 
    UNKNOWN,
    NONE
    
}
